"""Recipe synthesis.

`sparkrun run` takes a recipe, not a HuggingFace model id, and a recipe's
``command`` template decides which overrides actually reach the runtime. A
stock registry recipe templates whatever its author cared about, which is
usually tensor parallel and nothing else -- so ``--pp 2`` against a stock
recipe is accepted, exits zero, and runs TP=1/PP=1.

We therefore synthesize a recipe per deployment whose command template
references every knob the planner and fit gate decided on. The synthesized
file is deterministic: same inputs, same bytes, same path. That keeps
render_command pure and makes the rendered command safe for the UI to show.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence

from control_plane.contracts import ModelShape, ParallelismPlan, SpeculativeSpec

from .flags import (
    RuntimeSpec,
    llamacpp_model_spec,
    render_cudagraph_capture_sizes,
    render_kv_cache_dtype,
    render_quantization,
    render_speculative_config,
    runtime_spec,
)

RECIPE_HEADER = "# Generated by derate. Do not edit; regenerated on every launch.\n"

#: M-22: characters plain-scalar YAML would read as syntax rather than the
#: start of an ordinary value (block/flow indicators, comments, anchors,
#: tags, aliases, quotes). A value starting with one of these could change
#: what the generated recipe means even without a newline.
_YAML_LEADING_DANGEROUS = set("-?:,[]{}#&*!|>'\"%@`")


#: M-22, second half. YAML-safety is not sufficient on its own for any value
#: that reaches the command template. sparkrun injects the recipe's ``model:``
#: into the substitution namespace (core/recipe.py, ``base.setdefault("model",
#: self.model)``), substitutes it into ``{model}``, and the executor runs the
#: rendered string under ``bash -c`` inside a container whose sparkrun defaults
#: are privileged with host networking. So ``org/name;curl x|sh`` -- no newline,
#: no control character, and a harmless leading letter -- passes every check
#: below and then executes. Anything interpolated into the command must match
#: this grammar, which covers every real HuggingFace id including a quant tag
#: (``TheBloke/Llama-2-7B-Chat-GGUF:Q4_K_M``) *and* a local model -- resolver.py
#: also accepts a local directory or a local ``.gguf`` file and hands its
#: (possibly absolute, possibly ``~``-relative) path straight through as
#: ``model_id`` -- while still admitting nothing a shell reads as syntax. The
#: leading-character class is therefore wider than the "rest of the string"
#: class only to the extent real paths need (``/``, ``.``, ``~``); it does not
#: add any character the body class did not already allow elsewhere in the
#: string, so it does not reopen the metacharacter hole this grammar exists
#: to close.
_COMMAND_SAFE = re.compile(r"\A[A-Za-z0-9/.~][A-Za-z0-9._:/~-]*\Z")

# Path-like forms (~/x, ./x, ../x, /x) are legitimate model locations, but the
# bare spellings are hazards on their own: YAML reads a lone "~" as null, and
# "." / ".." name no model at all — they only ever appear in an attack or a
# typo, so refuse them outright rather than letting them reach a recipe.
_COMMAND_BARE_REJECTS = frozenset({"~", ".", ".."})


def _check_command_safe(value: str, field: str) -> None:
    """Reject a string that is not safe to substitute into the shell command.

    Stricter than _check_yaml_safe and for a different reason: that one
    protects the file we write, this one protects the command sparkrun runs
    from it. An allowlist, because the blocklist for ``bash -c`` is unbounded.
    """
    if value in _COMMAND_BARE_REJECTS or not _COMMAND_SAFE.match(value):
        raise ValueError(
            "%s is not safe to substitute into the launch command: %r. "
            "Expected letters, digits, and . _ - : / ~ only, starting with a "
            "letter, digit, / . or ~ (and never a bare ~, . or ..)." % (field, value)
        )


def _check_yaml_safe(value: str, field: str) -> None:
    """Reject a string that is not safe to interpolate, unquoted, into a
    line of the recipe YAML this module writes and sparkrun executes.

    ``synthesize`` builds the recipe body with plain ``%s`` interpolation --
    nothing here is YAML-escaped or quoted. A model_id or served_name that
    reached this function from an API request could otherwise carry a
    newline and open a new top-level key of its own choosing, including
    ``command:``, in a file sparkrun runs. Legitimate HuggingFace ids
    (``org/name``, dots, dashes, underscores, a quant-tag colon) all pass;
    this only blocks what plain-scalar YAML cannot represent safely
    unquoted.
    """
    if not value:
        raise ValueError("%s must not be empty" % field)
    if "\n" in value or "\r" in value:
        raise ValueError(
            "%s contains a newline, which could inject a new key (including "
            "command:) into the generated recipe YAML: %r" % (field, value)
        )
    if any(unicodedata.category(ch) == "Cc" for ch in value):
        raise ValueError(
            "%s contains a control character, which is not safe to write "
            "unquoted into the generated recipe YAML: %r" % (field, value)
        )
    if value[0].isspace() or value[0] in _YAML_LEADING_DANGEROUS:
        raise ValueError(
            "%s starts with %r, a character YAML would parse as syntax "
            "rather than the start of a plain scalar" % (field, value[0])
        )


#: M-22, third variant. Extra-arg tokens are not identifiers -- they are the
#: caller's own runtime flags (``--quantization``, ``modelopt_fp4``, a
#: ``--flag=value`` pair) -- so this grammar is wider than _COMMAND_SAFE's
#: (it admits a leading ``-``/``--`` and an ``=``) but the reason for it is
#: identical: each token lands, one per continuation line, inside the
#: recipe's ``command: |`` block, which sparkrun runs under ``bash -c``
#: inside a privileged, host-networked container. An allowlist, not a
#: blocklist, for the same reason _check_command_safe is one: the blocklist
#: for ``bash -c`` is unbounded.
_EXTRA_ARG_SAFE = re.compile(r"\A-{0,2}[A-Za-z0-9_./~][A-Za-z0-9_.:/~=,+-]*\Z")


def _check_extra_arg_safe(token: str, index: int, field: str) -> None:
    if not token or not _EXTRA_ARG_SAFE.match(token):
        raise ValueError(
            "%s[%d] is not safe to substitute into the launch "
            "command: %r. Expected an optional leading - or --, then "
            "letters, digits, and . _ - : / ~ = , + only." % (field, index, token)
        )


def check_extra_args_safe(extra_args: Sequence[str], field: str = "extra_args") -> None:
    """Run the M-22 check on every caller-supplied CLI token.

    Mirrors check_recipe_identifiers: called both by synthesize() and by
    DeploymentManager.launch() before any record exists, so the two call
    sites can never drift on what "safe" means. The same grammar covers
    *extra_args* (appended after the generated command) and *custom_command*
    (replaces it) -- both land, one token per continuation line, in the same
    ``command: |`` block, so *field* only changes which name an error names.
    """
    for index, token in enumerate(extra_args):
        _check_extra_arg_safe(token, index, field)


#: M-22, fourth variant. The container image became caller-supplied the day
#: a deployment could choose its own, and it is a different shape from every
#: other value here: a registry reference, which needs ``/`` for the path,
#: one ``:`` for a tag, another for a registry port, and ``@sha256:`` for a
#: digest pin -- the one form worth pinning and the one no other grammar in
#: this file admits.
#:
#: It does NOT reach the ``command: |`` block; it lands on the recipe's
#: ``container:`` key, so _COMMAND_SAFE was never what guarded it and
#: _check_yaml_safe alone was. sparkrun ``shlex.quote``s the image into every
#: command it builds from there (orchestration/executor_docker.py), so this
#: is not closing an injection hole that is open today. It exists for two
#: other reasons: a typo should come back as a refusal naming the expected
#: shape rather than a docker error forty seconds into a launch, and the
#: native launcher that replaces sparkrun will do its own quoting and inherit
#: that defence. An allowlist, for the same reason the others are.
_IMAGE_SAFE = re.compile(
    r"\A"
    r"[A-Za-z0-9][A-Za-z0-9._-]*"          # host, or the first path component
    r"(?::[0-9]+)?"                        # a registry port, never a tag here
    r"(?:/[A-Za-z0-9][A-Za-z0-9._-]*)*"    # the rest of the repository path
    r"(?::[A-Za-z0-9_][A-Za-z0-9._-]*)?"   # optional tag
    r"(?:@sha256:[A-Fa-f0-9]{64})?"        # optional digest pin
    r"\Z"
)


def check_image_safe(image: str | None, field: str = "image") -> None:
    """Run the M-22 check on a caller-supplied container image reference.

    Mirrors check_extra_args_safe: called both by synthesize() and by
    DeploymentManager.launch() before any record exists, so the two call
    sites can never drift on what "safe" means.

    ``None`` and ``""`` are not refusals -- both mean "the runtime's own
    pinned default", which is what synthesize() resolves them to through
    container_image(). Only a non-empty string that is not a registry
    reference is refused.

    Only ``sha256`` digests are admitted. That is narrower than the OCI
    spec allows and is deliberate: it is the only algorithm anything in this
    estate produces, and a grammar is easier to widen later than to narrow
    once somebody depends on it.
    """
    if not image:
        return
    _check_yaml_safe(image, field)
    if not _IMAGE_SAFE.match(image):
        raise ValueError(
            "%s is not a container image reference: %r. Expected "
            "[registry[:port]/]repository[:tag][@sha256:<64 hex>], using "
            "letters, digits, and . _ - / only." % (field, image)
        )


def check_recipe_identifiers(model_id: str, served_name: str) -> None:
    """Run every M-22 safety check on the two identifiers that reach both
    the recipe YAML and the rendered command.

    ``synthesize`` calls this itself, so it is safe on its own. It is also
    exposed here so ``DeploymentManager.launch`` can run the identical check
    synchronously -- before a LAUNCHING record or launch worker thread ever
    exists -- rather than only discovering a hostile model_id or served_name
    when the async launch worker calls ``synthesize`` and flips the record to
    FAILED after the fact. Keeping one function means the two call sites can
    never drift apart on what "safe" means.
    """
    _check_yaml_safe(model_id, "model_id")
    _check_yaml_safe(served_name, "served_name")
    _check_command_safe(model_id, "model_id")
    _check_command_safe(served_name, "served_name")


@dataclass(frozen=True)
class RecipeSpec:
    """A synthesized recipe: its content, and where it will be written."""

    path: Path
    content: str
    served_name: str
    runtime: RuntimeSpec

    @property
    def digest(self) -> str:
        return hashlib.sha256(self.content.encode()).hexdigest()[:12]


def container_image(spec: RuntimeSpec, env: dict[str, str] | None = None) -> str:
    """Container image for *spec*, overridable per-runtime by env var."""
    env = os.environ if env is None else env
    return env.get(spec.default_image_env) or spec.default_image


def _serve_command(
    spec: RuntimeSpec,
    plan: ParallelismPlan,
    extra_args: tuple[str, ...] = (),
    *,
    kv_cache_memory_bytes: int | None = None,
    speculative_config: str | None = None,
    enforce_eager: bool = False,
    cudagraph_capture_sizes: str | None = None,
    kv_cache_dtype: str | None = None,
    quantization: str | None = None,
) -> str:
    """The command template, with conditional flags baked in.

    Conditionals cannot be templated -- there is no ``{if}`` in a recipe --
    so expert parallel is appended at synthesis time. Everything with a
    numeric value stays a ``{placeholder}`` so the sparkrun CLI overrides in
    render_command actually bind.

    *extra_args* must already have passed check_extra_args_safe -- this
    function does not check them again, exactly like the model_id/served_name
    values it also trusts by this point.
    """
    command = spec.command_template
    if plan.expert_parallel > 1 and spec.expert_parallel_arg:
        command += " \\\n    %s" % spec.expert_parallel_arg
    # Same reason as expert parallel: no {if} in a recipe, so a flag that is
    # only sometimes wanted is appended here. Sometimes, because a runtime
    # that cannot be told its KV size has no such flag, and because a caller
    # without a fit breakdown to quote has no number to put in it -- and a
    # wrong number here is allocated exactly, unlike a fraction.
    if kv_cache_memory_bytes and spec.kv_cache_bytes_arg:
        command += " \\\n    %s" % spec.kv_cache_bytes_arg
    # Third conditional flag, same shape as the two above, and the one whose
    # value is not a number. `synthesize` builds it through
    # flags.render_speculative_config, which validates the rendered JSON
    # against a whole-string grammar before it can get here -- so unlike
    # extra_args this is not caller text that passed a token check, it is a
    # string this process composed from an enum member and an int.
    if speculative_config and spec.speculative_config_arg:
        command += " \\\n    %s" % spec.speculative_config_arg
    # Fourth and fifth conditional flags, same shape as the three above.
    # enforce_eager is a bare literal, nothing to render. cudagraph_capture_sizes
    # arrives already rendered by flags.render_cudagraph_capture_sizes, exactly
    # like speculative_config arrives already rendered by
    # flags.render_speculative_config.
    if enforce_eager and spec.enforce_eager_arg:
        command += " \\\n    %s" % spec.enforce_eager_arg
    if cudagraph_capture_sizes and spec.cudagraph_capture_sizes_arg:
        command += " \\\n    %s" % spec.cudagraph_capture_sizes_arg
    # Sixth, and the partner of kv_cache_bytes_arg above: that one caps how
    # many bytes the cache may use, this one sets how wide each entry is. The
    # fit gate has always priced the width and could only ever send the cap,
    # which is how a request for fp8 bought a halved budget filled with fp16.
    if kv_cache_dtype and spec.kv_cache_dtype_arg:
        command += " \\\n    %s" % spec.kv_cache_dtype_arg
    # Seventh, and the heaviest of them: this one re-prices the WEIGHTS term,
    # not the cache. Arrives already rendered by flags.render_quantization,
    # which raises on a scheme this image's registry does not hold rather
    # than letting the runtime discover it at load.
    if quantization and spec.quantization_arg:
        command += " \\\n    %s" % spec.quantization_arg
    if extra_args:
        command += " \\\n    %s" % " ".join(extra_args)
    return command


def _custom_serve_command(spec: RuntimeSpec, custom_command: tuple[str, ...]) -> str:
    """The command when the operator supplies the whole runtime invocation
    in place of the plan-derived flags ``_serve_command`` builds.

    Only ``{model}`` -- still the fit gate's own resolved id, never operator
    text, so a custom launch cannot start a different model than the one the
    Verdict card judged -- and the three flags the gateway needs to route to
    this deployment survive: host, port, served_model_name. They are
    appended LAST, not first, so they win however each runtime's own
    argument parser resolves a repeated flag (every one of them, being an
    ordinary argparse table, takes the last occurrence) even if the
    operator's own text happens to repeat one of them.

    The served name is spelled per runtime (``RuntimeSpec.served_name_arg``)
    and the other two are not. That asymmetry is real rather than tidy:
    ``--host`` and ``--port`` are the same token everywhere this launches,
    and llama-server calls the third ``--alias`` and exits on an argument it
    does not recognise.

    Nothing else the planner decided -- tensor/pipeline parallel, context,
    concurrency, gpu_memory_utilization -- reaches this command at all: the
    Verdict card still shows what the fit gate computed for them, but here
    that is informational, not what launches.

    *custom_command* must already have passed check_extra_args_safe, exactly
    like *extra_args* in ``_serve_command``.
    """
    command = spec.custom_command_prefix
    if custom_command:
        command += " \\\n    %s" % " ".join(custom_command)
    command += " \\\n    --host {host} \\\n    --port {port}"
    command += " \\\n    %s {served_model_name}" % spec.served_name_arg
    return command


def synthesize(
    shape: ModelShape,
    plan: ParallelismPlan,
    runtime: str,
    context_length: int,
    max_concurrent_seqs: int,
    served_name: str,
    *,
    port: int,
    gpu_memory_utilization: float,
    kv_cache_memory_bytes: int | None = None,
    speculative: SpeculativeSpec | None = None,
    recipe_dir: Path,
    image: str | None = None,
    extra_args: tuple[str, ...] = (),
    custom_command: tuple[str, ...] = (),
    enforce_eager: bool = False,
    cudagraph_capture_sizes: tuple[int, ...] | None = None,
    kv_dtype: str | None = None,
    quantization: str | None = None,
    nccl_env: Mapping[str, str] | None = None,
) -> RecipeSpec:
    """Build the recipe for one deployment. Pure: touches no filesystem."""
    # M-22: shape.model_id and served_name both flow from an API request
    # (served_name may also just be default_served_name(shape), i.e. still
    # derived from model_id) and both land verbatim in the YAML body below,
    # and both reach the command template too -- model_id as {model} via
    # sparkrun's own namespace injection, served_name as {served_model_name}
    # through defaults below. check_recipe_identifiers runs both the YAML
    # check and the stricter command-grammar check on each.
    # The id that reaches the recipe is not always the id derate resolved.
    # `llamacpp_model_spec` rewrites an `hf://owner/repo/file.gguf` reference
    # into the `owner/repo:QUANT` spelling sparkrun's llama-cpp plugin parses,
    # and returns everything else untouched -- so for the other three runtimes
    # this line is the identity.
    #
    # Translated BEFORE the safety check, never after: the check exists to
    # protect the command sparkrun builds, so it has to run on the string that
    # actually gets there.
    launch_model_id = llamacpp_model_spec(shape.model_id)
    check_recipe_identifiers(launch_model_id, served_name)
    # extra_args and custom_command are the third M-22 surface: caller-supplied
    # CLI tokens that reach the command block directly (see
    # check_extra_args_safe). They are alternatives, not a pair -- one appends
    # to the generated command, the other replaces it, and sending both would
    # leave it ambiguous which the operator actually meant.
    check_extra_args_safe(extra_args)
    check_extra_args_safe(custom_command, field="custom_command")
    if extra_args and custom_command:
        raise ValueError(
            "extra_args and custom_command are mutually exclusive: extra_args "
            "appends to the generated serve command, custom_command replaces "
            "it, and a request cannot mean both at once"
        )
    if enforce_eager and cudagraph_capture_sizes:
        raise ValueError(
            "enforce_eager and cudagraph_capture_sizes are mutually exclusive: "
            "enforce_eager disables CUDA graph capture entirely, leaving "
            "nothing for a trimmed capture list to apply to"
        )

    spec = runtime_spec(runtime)
    img = image or container_image(spec)
    # check_image_safe covers _check_yaml_safe and adds the registry-reference
    # grammar. Run against the RESOLVED image, not the argument: the default
    # comes from an environment variable an operator set, and a typo there
    # should be refused here rather than forty seconds into a docker pull.
    check_image_safe(img, "container image")

    defaults = [
        ("host", "0.0.0.0"),
        ("port", port),
        ("served_model_name", served_name),
        ("tensor_parallel", plan.tensor_parallel),
        ("pipeline_parallel", plan.pipeline_parallel),
        ("max_model_len", context_length),
        (spec.max_seqs_key, max_concurrent_seqs),
        ("gpu_memory_utilization", "%.2f" % gpu_memory_utilization),
    ]
    # A context flag that sizes a shared pool needs the whole pool, not one
    # sequence's share. llama.cpp divides `--ctx-size` by its slot count --
    # measured on the pinned image, see `RuntimeSpec.context_is_shared_pool` --
    # so handing it `context_length` would serve every request
    # `context_length / max_concurrent_seqs` while the Verdict card, the
    # deployment record and the fit gate all said otherwise.
    #
    # Emitted as its own key rather than by rewriting `max_model_len`, because
    # that one is still the per-sequence number every other part of this system
    # means by "context" -- including the `derate_plan` line below and the
    # adoption parser, which reads this runtime's own `--ctx-size` back.
    if spec.context_is_shared_pool:
        defaults.append(("ctx_size", context_length * max(1, max_concurrent_seqs)))
    if kv_cache_memory_bytes and spec.kv_cache_bytes_arg:
        defaults.append(("kv_cache_memory_bytes", int(kv_cache_memory_bytes)))
    # Rendered here, not by the caller: `render_kv_cache_dtype` RAISES on a
    # dtype this build cannot request, so the failure lands before a recipe
    # exists rather than as a flag silently missing from one.
    rendered_kv_dtype = render_kv_cache_dtype(kv_dtype)
    if rendered_kv_dtype and spec.kv_cache_dtype_arg:
        defaults.append(("kv_cache_dtype", rendered_kv_dtype))
    # Same contract as the line above, one term heavier: this decides how wide
    # each WEIGHT is, which the fit gate has already budgeted for.
    rendered_quantization = render_quantization(quantization)
    if rendered_quantization and spec.quantization_arg:
        defaults.append(("quantization", rendered_quantization))
    speculative_config = None
    if speculative is not None and spec.speculative_config_arg:
        speculative_config = render_speculative_config(
            speculative.method.value,
            speculative.num_speculative_tokens,
            speculative.model,
        )
        # JSON-quoted, for the same reason derate_extra_args below is and with
        # a sharper edge: this value STARTS with `{`, which a plain YAML scalar
        # reads as a flow mapping. Written bare it would not be a malformed
        # string, it would parse cleanly into a dict, and sparkrun would
        # substitute that dict's Python repr -- single quotes and all -- into a
        # command already wrapped in single quotes. A double-quoted YAML scalar
        # keeps it the string this process built.
        defaults.append(("speculative_config", json.dumps(speculative_config)))
    cudagraph_capture_sizes_rendered = None
    if cudagraph_capture_sizes and spec.cudagraph_capture_sizes_arg:
        # Plain digits and single spaces, never JSON-quoted like
        # speculative_config above: the rendered value never starts with `{`,
        # so plain-scalar YAML reads it as an ordinary string either way.
        cudagraph_capture_sizes_rendered = render_cudagraph_capture_sizes(
            cudagraph_capture_sizes
        )
        defaults.append(("cudagraph_capture_sizes", cudagraph_capture_sizes_rendered))
    if plan.expert_parallel > 1:
        defaults.append(("expert_parallel", plan.expert_parallel))
    if plan.data_parallel > 1:
        defaults.append(("data_parallel", plan.data_parallel))

    lines = [
        RECIPE_HEADER,
        "model: %s\n" % launch_model_id,
        "runtime: %s\n" % spec.sparkrun_runtime,
        "min_nodes: %d\n" % len(plan.node_ids),
        "container: %s\n" % img,
        "\n",
        "metadata:\n",
        "  description: derate %s, %s\n" % (served_name, plan.kind.value),
        "  derate_plan: %s\n" % _plan_summary(plan),
    ]
    if custom_command:
        # Same quoting reasoning as derate_extra_args below.
        lines.append(
            "  derate_custom_command: %s\n" % json.dumps(" ".join(custom_command))
        )
    elif extra_args:
        # JSON-quoted rather than a plain scalar: extra_args routinely start
        # with "-" or "--", which plain-scalar YAML would read as a block
        # sequence indicator rather than the start of an ordinary value (see
        # _YAML_LEADING_DANGEROUS above). A double-quoted YAML scalar has no
        # such leading-character ambiguity, and JSON's quoting is valid YAML.
        lines.append(
            "  derate_extra_args: %s\n" % json.dumps(" ".join(extra_args))
        )
    lines += [
        "\n",
        "defaults:\n",
    ]
    lines += ["  %s: %s\n" % (k, v) for k, v in defaults]
    # Where this runtime's compiled artifacts go, when it has any. sparkrun
    # merges a recipe's `env:` into the container's environment ahead of its
    # own additions (runtimes/base.py) and the docker executor emits each as
    # `-e`, so this is the supported channel for it -- and the only one, since
    # the recipe format has no way to ask for a volume. Not run through the
    # safety checks above on purpose: unlike model_id and served_name these are
    # module constants from flags.py and never touch a request.
    #
    # NCCL settings ride the same block, and are the one part of it that DOES
    # come from a request. They are validated before they get here --
    # `flags.nccl_env_refusal` checks every name against the image's own
    # table, because NCCL ignores an unknown variable without warning and a
    # typo would otherwise produce a launch that reports as tuned and is not --
    # and every value is held to `_NCCL_VALUE_SAFE`, so nothing reaching this
    # line can carry a quote or a space into the rendered command.
    #
    # Sorted, so the same request renders the same recipe and the content hash
    # is stable.
    env_pairs = list(spec.cache_env) + sorted((nccl_env or {}).items())
    if env_pairs:
        lines += ["\n", "env:\n"]
        lines += ["  %s: %s\n" % (k, v) for k, v in env_pairs]

    # How the container itself is run, as opposed to what runs inside it.
    # sparkrun resolves these CLI > recipe > runtime-plugin defaults >
    # EXECUTOR_DEFAULTS, and its defaults describe a DGX Spark GPU workload --
    # `gpus: "all"` among them, which is a `docker run` that fails outright on
    # a machine with no NVIDIA runtime rather than a flag wasted there.
    #
    # Quoted, unlike the `env:` block above, because the values this currently
    # carries are EMPTY STRINGS: bare, plain-scalar YAML reads `gpus:` with
    # nothing after it as null, and null is "not set", which falls through to
    # sparkrun's default and reinstates the exact flag the entry exists to
    # remove. `""` and null are two different answers here and only one of
    # them is ours. Module constants from flags.py, never request text, for
    # the same reason `cache_env` is not run through the checks above.
    if spec.executor_config:
        lines += ["\n", "executor_config:\n"]
        lines += [
            "  %s: %s\n" % (k, json.dumps(v)) for k, v in spec.executor_config
        ]

    lines += ["\n", "command: |\n"]
    body = (
        _custom_serve_command(spec, custom_command)
        if custom_command
        else _serve_command(
            spec,
            plan,
            extra_args,
            kv_cache_memory_bytes=kv_cache_memory_bytes,
            kv_cache_dtype=rendered_kv_dtype,
            quantization=rendered_quantization,
            speculative_config=speculative_config,
            enforce_eager=enforce_eager,
            cudagraph_capture_sizes=cudagraph_capture_sizes_rendered,
        )
    )
    lines += ["  %s\n" % line for line in body.splitlines()]

    content = "".join(lines)
    name = "%s-%s-%s.yaml" % (
        _slug(served_name),
        spec.name,
        hashlib.sha256(content.encode()).hexdigest()[:8],
    )
    return RecipeSpec(
        path=Path(recipe_dir) / name,
        content=content,
        served_name=served_name,
        runtime=spec,
    )


def materialize(recipe: RecipeSpec) -> Path:
    """Write the recipe to disk. Idempotent: identical content, identical path."""
    recipe.path.parent.mkdir(parents=True, exist_ok=True)
    tmp = recipe.path.with_suffix(recipe.path.suffix + ".tmp")
    tmp.write_text(recipe.content)
    tmp.replace(recipe.path)
    return recipe.path


def _plan_summary(plan: ParallelismPlan) -> str:
    parts = []
    for label, value in (
        ("TP", plan.tensor_parallel),
        ("PP", plan.pipeline_parallel),
        ("EP", plan.expert_parallel),
        ("DP", plan.data_parallel),
    ):
        if value > 1:
            parts.append("%s%d" % (label, value))
    return " ".join(parts) or "single node"


def _slug(text: str) -> str:
    out = [c.lower() if c.isalnum() else "-" for c in text]
    return "".join(out).strip("-")[:64] or "model"
