"""Recipe synthesis.

`sparkrun run` takes a recipe, not a HuggingFace model id, and a recipe's
``command`` template decides which overrides actually reach the runtime. A
stock registry recipe templates whatever its author cared about, which is
usually tensor parallel and nothing else -- so ``--pp 2`` against a stock
recipe is accepted, exits zero, and runs TP=1/PP=1.

We therefore synthesize a recipe per deployment whose command template
references every knob the planner and fit gate decided on. The synthesized
file is deterministic: same inputs, same bytes, same path. That keeps
render_command pure and makes the rendered command safe for Agent H to show.
"""

from __future__ import annotations

import hashlib
import os
import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path

from control_plane.contracts import ModelShape, ParallelismPlan

from .flags import RuntimeSpec, runtime_spec

RECIPE_HEADER = "# Generated by sparkplane. Do not edit; regenerated on every launch.\n"

#: M-22: characters plain-scalar YAML would read as syntax rather than the
#: start of an ordinary value (block/flow indicators, comments, anchors,
#: tags, aliases, quotes). A value starting with one of these could change
#: what the generated recipe means even without a newline.
_YAML_LEADING_DANGEROUS = set("-?:,[]{}#&*!|>'\"%@`")


#: M-22, second half. YAML-safety is not sufficient on its own for any value
#: that reaches the command template. sparkrun injects the recipe's ``model:``
#: into the substitution namespace (core/recipe.py, ``base.setdefault("model",
#: self.model)``), substitutes it into ``{model}``, and the executor runs the
#: rendered string under ``bash -c`` inside a container whose sparkrun defaults
#: are privileged with host networking. So ``org/name;curl x|sh`` -- no newline,
#: no control character, and a harmless leading letter -- passes every check
#: below and then executes. Anything interpolated into the command must match
#: this grammar, which covers every real HuggingFace id including a quant tag
#: (``TheBloke/Llama-2-7B-Chat-GGUF:Q4_K_M``) *and* a local model -- resolver.py
#: also accepts a local directory or a local ``.gguf`` file and hands its
#: (possibly absolute, possibly ``~``-relative) path straight through as
#: ``model_id`` -- while still admitting nothing a shell reads as syntax. The
#: leading-character class is therefore wider than the "rest of the string"
#: class only to the extent real paths need (``/``, ``.``, ``~``); it does not
#: add any character the body class did not already allow elsewhere in the
#: string, so it does not reopen the metacharacter hole this grammar exists
#: to close.
_COMMAND_SAFE = re.compile(r"\A[A-Za-z0-9/.~][A-Za-z0-9._:/~-]*\Z")

# Path-like forms (~/x, ./x, ../x, /x) are legitimate model locations, but the
# bare spellings are hazards on their own: YAML reads a lone "~" as null, and
# "." / ".." name no model at all — they only ever appear in an attack or a
# typo, so refuse them outright rather than letting them reach a recipe.
_COMMAND_BARE_REJECTS = frozenset({"~", ".", ".."})


def _check_command_safe(value: str, field: str) -> None:
    """Reject a string that is not safe to substitute into the shell command.

    Stricter than _check_yaml_safe and for a different reason: that one
    protects the file we write, this one protects the command sparkrun runs
    from it. An allowlist, because the blocklist for ``bash -c`` is unbounded.
    """
    if value in _COMMAND_BARE_REJECTS or not _COMMAND_SAFE.match(value):
        raise ValueError(
            "%s is not safe to substitute into the launch command: %r. "
            "Expected letters, digits, and . _ - : / ~ only, starting with a "
            "letter, digit, / . or ~ (and never a bare ~, . or ..)." % (field, value)
        )


def _check_yaml_safe(value: str, field: str) -> None:
    """Reject a string that is not safe to interpolate, unquoted, into a
    line of the recipe YAML this module writes and sparkrun executes.

    ``synthesize`` builds the recipe body with plain ``%s`` interpolation --
    nothing here is YAML-escaped or quoted. A model_id or served_name that
    reached this function from an API request could otherwise carry a
    newline and open a new top-level key of its own choosing, including
    ``command:``, in a file sparkrun runs. Legitimate HuggingFace ids
    (``org/name``, dots, dashes, underscores, a quant-tag colon) all pass;
    this only blocks what plain-scalar YAML cannot represent safely
    unquoted.
    """
    if not value:
        raise ValueError("%s must not be empty" % field)
    if "\n" in value or "\r" in value:
        raise ValueError(
            "%s contains a newline, which could inject a new key (including "
            "command:) into the generated recipe YAML: %r" % (field, value)
        )
    if any(unicodedata.category(ch) == "Cc" for ch in value):
        raise ValueError(
            "%s contains a control character, which is not safe to write "
            "unquoted into the generated recipe YAML: %r" % (field, value)
        )
    if value[0].isspace() or value[0] in _YAML_LEADING_DANGEROUS:
        raise ValueError(
            "%s starts with %r, a character YAML would parse as syntax "
            "rather than the start of a plain scalar" % (field, value[0])
        )


def check_recipe_identifiers(model_id: str, served_name: str) -> None:
    """Run every M-22 safety check on the two identifiers that reach both
    the recipe YAML and the rendered command.

    ``synthesize`` calls this itself, so it is safe on its own. It is also
    exposed here so ``DeploymentManager.launch`` can run the identical check
    synchronously -- before a LAUNCHING record or launch worker thread ever
    exists -- rather than only discovering a hostile model_id or served_name
    when the async launch worker calls ``synthesize`` and flips the record to
    FAILED after the fact. Keeping one function means the two call sites can
    never drift apart on what "safe" means.
    """
    _check_yaml_safe(model_id, "model_id")
    _check_yaml_safe(served_name, "served_name")
    _check_command_safe(model_id, "model_id")
    _check_command_safe(served_name, "served_name")


@dataclass(frozen=True)
class RecipeSpec:
    """A synthesized recipe: its content, and where it will be written."""

    path: Path
    content: str
    served_name: str
    runtime: RuntimeSpec

    @property
    def digest(self) -> str:
        return hashlib.sha256(self.content.encode()).hexdigest()[:12]


def container_image(spec: RuntimeSpec, env: dict[str, str] | None = None) -> str:
    """Container image for *spec*, overridable per-runtime by env var."""
    env = os.environ if env is None else env
    return env.get(spec.default_image_env) or spec.default_image


def _serve_command(spec: RuntimeSpec, plan: ParallelismPlan) -> str:
    """The command template, with conditional flags baked in.

    Conditionals cannot be templated -- there is no ``{if}`` in a recipe --
    so expert parallel is appended at synthesis time. Everything with a
    numeric value stays a ``{placeholder}`` so the sparkrun CLI overrides in
    render_command actually bind.
    """
    command = spec.command_template
    if plan.expert_parallel > 1 and spec.expert_parallel_arg:
        command += " \\\n    %s" % spec.expert_parallel_arg
    return command


def synthesize(
    shape: ModelShape,
    plan: ParallelismPlan,
    runtime: str,
    context_length: int,
    max_concurrent_seqs: int,
    served_name: str,
    *,
    port: int,
    gpu_memory_utilization: float,
    recipe_dir: Path,
    image: str | None = None,
) -> RecipeSpec:
    """Build the recipe for one deployment. Pure: touches no filesystem."""
    # M-22: shape.model_id and served_name both flow from an API request
    # (served_name may also just be default_served_name(shape), i.e. still
    # derived from model_id) and both land verbatim in the YAML body below,
    # and both reach the command template too -- model_id as {model} via
    # sparkrun's own namespace injection, served_name as {served_model_name}
    # through defaults below. check_recipe_identifiers runs both the YAML
    # check and the stricter command-grammar check on each.
    check_recipe_identifiers(shape.model_id, served_name)

    spec = runtime_spec(runtime)
    img = image or container_image(spec)
    _check_yaml_safe(img, "container image")

    defaults = [
        ("host", "0.0.0.0"),
        ("port", port),
        ("served_model_name", served_name),
        ("tensor_parallel", plan.tensor_parallel),
        ("pipeline_parallel", plan.pipeline_parallel),
        ("max_model_len", context_length),
        (spec.max_seqs_key, max_concurrent_seqs),
        ("gpu_memory_utilization", "%.2f" % gpu_memory_utilization),
    ]
    if plan.expert_parallel > 1:
        defaults.append(("expert_parallel", plan.expert_parallel))
    if plan.data_parallel > 1:
        defaults.append(("data_parallel", plan.data_parallel))

    lines = [
        RECIPE_HEADER,
        "model: %s\n" % shape.model_id,
        "runtime: %s\n" % spec.sparkrun_runtime,
        "min_nodes: %d\n" % len(plan.node_ids),
        "container: %s\n" % img,
        "\n",
        "metadata:\n",
        "  description: sparkplane %s, %s\n" % (served_name, plan.kind.value),
        "  sparkplane_plan: %s\n" % _plan_summary(plan),
        "\n",
        "defaults:\n",
    ]
    lines += ["  %s: %s\n" % (k, v) for k, v in defaults]
    lines += ["\n", "command: |\n"]
    lines += ["  %s\n" % line for line in _serve_command(spec, plan).splitlines()]

    content = "".join(lines)
    name = "%s-%s-%s.yaml" % (
        _slug(served_name),
        spec.name,
        hashlib.sha256(content.encode()).hexdigest()[:8],
    )
    return RecipeSpec(
        path=Path(recipe_dir) / name,
        content=content,
        served_name=served_name,
        runtime=spec,
    )


def materialize(recipe: RecipeSpec) -> Path:
    """Write the recipe to disk. Idempotent: identical content, identical path."""
    recipe.path.parent.mkdir(parents=True, exist_ok=True)
    tmp = recipe.path.with_suffix(recipe.path.suffix + ".tmp")
    tmp.write_text(recipe.content)
    tmp.replace(recipe.path)
    return recipe.path


def _plan_summary(plan: ParallelismPlan) -> str:
    parts = []
    for label, value in (
        ("TP", plan.tensor_parallel),
        ("PP", plan.pipeline_parallel),
        ("EP", plan.expert_parallel),
        ("DP", plan.data_parallel),
    ):
        if value > 1:
            parts.append("%s%d" % (label, value))
    return " ".join(parts) or "single node"


def _slug(text: str) -> str:
    out = [c.lower() if c.isalnum() else "-" for c in text]
    return "".join(out).strip("-")[:64] or "model"
