"""Recipe synthesis.

`sparkrun run` takes a recipe, not a HuggingFace model id, and a recipe's
``command`` template decides which overrides actually reach the runtime. A
stock registry recipe templates whatever its author cared about, which is
usually tensor parallel and nothing else -- so ``--pp 2`` against a stock
recipe is accepted, exits zero, and runs TP=1/PP=1.

We therefore synthesize a recipe per deployment whose command template
references every knob the planner and fit gate decided on. The synthesized
file is deterministic: same inputs, same bytes, same path. That keeps
render_command pure and makes the rendered command safe for Agent H to show.
"""

from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass
from pathlib import Path

from control_plane.contracts import ModelShape, ParallelismPlan

from .flags import RuntimeSpec, runtime_spec

RECIPE_HEADER = "# Generated by sparkplane. Do not edit; regenerated on every launch.\n"


@dataclass(frozen=True)
class RecipeSpec:
    """A synthesized recipe: its content, and where it will be written."""

    path: Path
    content: str
    served_name: str
    runtime: RuntimeSpec

    @property
    def digest(self) -> str:
        return hashlib.sha256(self.content.encode()).hexdigest()[:12]


def container_image(spec: RuntimeSpec, env: dict[str, str] | None = None) -> str:
    """Container image for *spec*, overridable per-runtime by env var."""
    env = os.environ if env is None else env
    return env.get(spec.default_image_env) or spec.default_image


def _serve_command(spec: RuntimeSpec, plan: ParallelismPlan) -> str:
    """The command template, with conditional flags baked in.

    Conditionals cannot be templated -- there is no ``{if}`` in a recipe --
    so expert parallel is appended at synthesis time. Everything with a
    numeric value stays a ``{placeholder}`` so the sparkrun CLI overrides in
    render_command actually bind.
    """
    command = spec.command_template
    if plan.expert_parallel > 1 and spec.expert_parallel_arg:
        command += " \\\n    %s" % spec.expert_parallel_arg
    return command


def synthesize(
    shape: ModelShape,
    plan: ParallelismPlan,
    runtime: str,
    context_length: int,
    max_concurrent_seqs: int,
    served_name: str,
    *,
    port: int,
    gpu_memory_utilization: float,
    recipe_dir: Path,
    image: str | None = None,
) -> RecipeSpec:
    """Build the recipe for one deployment. Pure: touches no filesystem."""
    spec = runtime_spec(runtime)
    img = image or container_image(spec)

    defaults = [
        ("host", "0.0.0.0"),
        ("port", port),
        ("served_model_name", served_name),
        ("tensor_parallel", plan.tensor_parallel),
        ("pipeline_parallel", plan.pipeline_parallel),
        ("max_model_len", context_length),
        (spec.max_seqs_key, max_concurrent_seqs),
        ("gpu_memory_utilization", "%.2f" % gpu_memory_utilization),
    ]
    if plan.expert_parallel > 1:
        defaults.append(("expert_parallel", plan.expert_parallel))
    if plan.data_parallel > 1:
        defaults.append(("data_parallel", plan.data_parallel))

    lines = [
        RECIPE_HEADER,
        "model: %s\n" % shape.model_id,
        "runtime: %s\n" % spec.sparkrun_runtime,
        "min_nodes: %d\n" % len(plan.node_ids),
        "container: %s\n" % img,
        "\n",
        "metadata:\n",
        "  description: sparkplane %s, %s\n" % (served_name, plan.kind.value),
        "  sparkplane_plan: %s\n" % _plan_summary(plan),
        "\n",
        "defaults:\n",
    ]
    lines += ["  %s: %s\n" % (k, v) for k, v in defaults]
    lines += ["\n", "command: |\n"]
    lines += ["  %s\n" % line for line in _serve_command(spec, plan).splitlines()]

    content = "".join(lines)
    name = "%s-%s-%s.yaml" % (
        _slug(served_name),
        spec.name,
        hashlib.sha256(content.encode()).hexdigest()[:8],
    )
    return RecipeSpec(
        path=Path(recipe_dir) / name,
        content=content,
        served_name=served_name,
        runtime=spec,
    )


def materialize(recipe: RecipeSpec) -> Path:
    """Write the recipe to disk. Idempotent: identical content, identical path."""
    recipe.path.parent.mkdir(parents=True, exist_ok=True)
    tmp = recipe.path.with_suffix(recipe.path.suffix + ".tmp")
    tmp.write_text(recipe.content)
    tmp.replace(recipe.path)
    return recipe.path


def _plan_summary(plan: ParallelismPlan) -> str:
    parts = []
    for label, value in (
        ("TP", plan.tensor_parallel),
        ("PP", plan.pipeline_parallel),
        ("EP", plan.expert_parallel),
        ("DP", plan.data_parallel),
    ):
        if value > 1:
            parts.append("%s%d" % (label, value))
    return " ".join(parts) or "single node"


def _slug(text: str) -> str:
    out = [c.lower() if c.isalnum() else "-" for c in text]
    return "".join(out).strip("-")[:64] or "model"
