"""Every HTTP route this project answers, dumped from the apps themselves.

``00-architecture.md`` section 4.8 introduces its route table with the claim
that "the UI codes against exactly this". It is a hand-maintained prose table,
and it is missing eleven routes that shipped -- setup, runtime management, node
labelling, links reach, model search. A route that exists and is not in the
table is undiscoverable to anyone taking the document at its word; a route in
the table that no longer exists is worse.

So the table stops being written by hand. Starlette already knows every path it
will answer, and asking it cannot be wrong. This dumps method and path only --
not the full OpenAPI schema -- because the fact worth pinning is which
endpoints exist, and a full schema would rewrite itself on every unrelated
signature change and train everyone to regenerate without reading the diff.

Both surfaces are covered: the coordinator's gateway and the node agent, which
are different apps on different ports and have never been listed together
anywhere.

    python3 -m control_plane.contracts.routes           # print it
    python3 -m control_plane.contracts.routes --write   # rewrite routes.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROUTES_PATH = Path(__file__).with_name("routes.json")

#: Starlette mounts and the catch-all UI handler answer paths that are not
#: endpoints, and listing them would be listing the filesystem.
_SKIP_KINDS = {"Mount", "WebSocketRoute"}

#: Methods every route reports whether or not it implements them.
_IMPLICIT = {"HEAD"}


def _gateway_app():
    from control_plane.gateway import GatewayDeps, GatewaySettings, create_app
    from control_plane.gateway.stubs import (
        StubDeployments,
        StubLinks,
        StubPlanner,
        StubProviders,
        StubRegistry,
        StubResolver,
    )
    from control_plane.fit.stub import StubFit

    deps = GatewayDeps(
        registry=StubRegistry(),
        links=StubLinks(),
        resolver=StubResolver(),
        fit=StubFit(),
        planner=StubPlanner(),
        deployments=StubDeployments(),
        providers=StubProviders(),
        settings=GatewaySettings(),
    )
    return create_app(deps)


def _agent_app():
    from control_plane.registry.agent import NodeAgent, create_agent_app
    from control_plane.registry.config import RegistryConfig

    return create_agent_app(NodeAgent(RegistryConfig.from_env({})))


def _walk(routes, prefix: str, out: list[dict]) -> None:
    """Flatten a route table, following included routers.

    FastAPI stopped copying an included router's routes onto the app and now
    holds a wrapper that defers to the original. A collector that only reads
    ``app.routes`` therefore sees four routes on a surface that answers a
    hundred and cheerfully reports the other ninety-six do not exist -- which
    is the same false confidence the hand-written table gives, arrived at by a
    more convincing route.
    """
    for route in routes:
        original = getattr(route, "original_router", None)
        if original is not None:
            context = getattr(route, "include_context", None)
            _walk(original.routes, prefix + (getattr(context, "prefix", "") or ""), out)
            continue

        path = getattr(route, "path", None)
        if path is None:
            continue
        kind = type(route).__name__
        if kind == "WebSocketRoute":
            out.append({"methods": ["WEBSOCKET"], "path": prefix + path})
            continue
        if kind in _SKIP_KINDS:
            continue
        methods = sorted(set(getattr(route, "methods", []) or []) - _IMPLICIT)
        if not methods:
            continue
        out.append({"methods": methods, "path": prefix + path})


def _collect(app) -> list[dict]:
    out: list[dict] = []
    _walk(app.routes, "", out)
    # Two routers may legitimately answer the same path with different methods;
    # the same (method, path) twice is a registration bug, so collapse on both.
    unique = {(tuple(r["methods"]), r["path"]): r for r in out}
    return sorted(unique.values(), key=lambda r: (r["path"], r["methods"]))


def build() -> dict:
    return {
        "note": (
            "Generated by control_plane/contracts/routes.py. Do not edit. "
            "Regenerate with: python3 -m control_plane.contracts.routes --write"
        ),
        "gateway": _collect(_gateway_app()),
        "agent": _collect(_agent_app()),
    }


def render(routes: dict | None = None) -> str:
    return json.dumps(routes if routes is not None else build(), indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help=f"rewrite {ROUTES_PATH.name}")
    args = parser.parse_args(argv)

    text = render()
    if args.write:
        ROUTES_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {ROUTES_PATH}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised as a CLI
    raise SystemExit(main())
